### PR TITLE
update to work with InfluxDB 1.5 and crystal 0.25.1

### PR DESCRIPTION
**Pull request by stakach**
Removed unused dependencies
Removed async mode as it was not safe

### CODE REVIEW

**Comment by stakach** [comment]
Happy to take over maintenance of this project if you want to add me as a collaborator

**Comment by jeromegn** [comment]
Hey, thanks for this PR!

How do you mean async mode was not safe?

**Comment by stakach** [comment]
The test crashed / failed with weird errors related to overlapped IO. I assume the crystal implementation of HTTP client has changed.
It won't crash using channels however then you wouldn't be able to use sync and channels simultaneously (given the current behaviour). I'm planning on rewriting it to use promises which would be async allowing you to ignore or wait for the result either in a sync or async manner

**Comment by jeromegn** [comment]
Sorry for the delay. I don't have time to manage this, so I added you as a collaborator.

**Comment by stakach** [comment]
Thanks man, I'll keep this pull open for now and commit once I've done some more real-world testing.

**Comment by stakach** [comment]
@jeromegn I don't seem to have write access - however this pull request is good to go now

**Comment by jeromegn** [comment]
@stakach it looks like you haven't accepted the invitation.

image

**Comment by stakach** [comment]
Thanks. Totally missed that invite.
One last thing, I can't remove the unmaintained message.

**Comment by jeromegn** [comment]
Just removed it for you! Let me know if you need anything else.

Feel free to fork or something if you'd rather have full control. I don't mind! I don't think that many people uses this shard.

**Pull request merged**
